# /dev-docs

Create comprehensive strategic plan and development documentation.

## Usage

```
/dev-docs [feature-name]
```

## What This Command Does

This command invokes the **strategic-plan-architect** agent to create a comprehensive plan for a feature or project.

1. Gathers context efficiently (without reading unnecessary files)
2. Creates a strategic plan with architecture, phases, and decisions
3. Generates three documentation files in `dev/active/`

## Parameters

- `feature-name` (required): Name of the feature/project (kebab-case recommended)

## Example

```
/dev-docs user-authentication
```

This will create:
- `dev/active/user-authentication-plan.md` - Strategic plan
- `dev/active/user-authentication-context.md` - Context and notes
- `dev/active/user-authentication-tasks.md` - Task checklist

## Output Files

### `[feature-name]-plan.md`

Contains:
- Overview and goals
- Architecture and components
- Implementation phases
- Technical decisions
- Risks and mitigation
- Testing strategy

### `[feature-name]-context.md`

Contains:
- Current state
- Relevant files and patterns
- Dependencies
- Notes for future sessions

### `[feature-name]-tasks.md`

Contains:
- Phase-by-phase task checklist
- Testing tasks
- Documentation tasks
- Review tasks

## Integration

Works well with:
- **Agent:** `strategic-plan-architect` (invoked automatically)
- **Skills:** All domain and guidelines skills (referenced in plan)
- **Commands:**
  - `/dev-docs-update` - Update docs before compaction
  - `/create-dev-docs` - Convert approved plan to implementation

## Workflow

1. **Create plan:** `/dev-docs feature-name`
2. **Review plan:** Check the generated files
3. **Iterate if needed:** Discuss changes with Claude
4. **Start implementation:** Use tasks.md as guide
5. **Update as you go:** Keep context.md current

## Notes

- Files are created in `dev/active/` to distinguish from completed work
- When feature is done, move to `dev/completed/`
- The agent will efficiently gather context using Grep/Glob
- Strategic plans help maintain context across multiple sessions

## Tips

**Good feature names:**
- `user-authentication`
- `payment-integration`
- `admin-dashboard`

**Avoid:**
- Too generic: `updates`, `changes`
- Too specific: `fix-bug-in-user-controller`

---

*Generated by: Claude Arsenal*
*Agent used: strategic-plan-architect*
